name: MSUpdate
run-name: Make MSUpdate ${{ inputs.options }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      makeversion:
        description: 'Target OS Version'
        required: true
        type: choice
        options:
          - w1164
          - w1164uup
          - w1064
          - w1064uup
          - w10lt2164
          - w10lt1964
          - w10lt1664

jobs:
  msupdate:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get rclone Config
        uses: actions/checkout@v4
        with:
          repository: xrgzs/rclone-action
          token: ${{ secrets.RCLONE_TOKEN }}
          path: bin

      - name: Change DNS Server
        shell: pwsh
        run: |
          $newDnsServers = @('1.1.1.1', '8.8.8.8')
          $networkAdapters = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }
          foreach ($adapter in $networkAdapters) {
              Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ResetServerAddresses
              Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ServerAddresses $newDnsServers
          }
          ipconfig /flushdns

      - name: Big Task
        shell: pwsh
        run: |
          $makeversion = "${{ inputs.makeversion }}"
          .\msupdate.ps1